PAIR NUMPY

In [1]:
import numpy as np

Creación y Indexación:
Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
arraya = np.random.randint(10,100, size=50)
arraya

array([79, 49, 30, 42, 10, 78, 70, 59, 80, 75, 23, 34, 93, 44, 67, 89, 28,
       46, 33, 49, 12, 58, 21, 34, 41, 88, 42, 86, 55, 54, 67, 92, 22, 29,
       92, 50, 13, 20, 56, 89, 94, 27, 63, 41, 33, 60, 41, 23, 16, 17],
      dtype=int32)

In [3]:
arraya[::5]

array([79, 78, 23, 89, 12, 88, 67, 50, 94, 60], dtype=int32)

Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
arrayb = np.random.randint(1,21, size=30)
arrayb

array([10, 19, 20, 17,  7, 11, 19, 11, 12,  3, 15,  5, 19, 20, 19,  4, 14,
        3, 13, 16,  8,  1,  4,  2,  1,  2,  7, 19,  1,  2], dtype=int32)

In [5]:
arrayb[1::2]

array([19, 17, 11, 11,  3,  5, 20,  4,  3, 16,  1,  2,  2, 19,  2],
      dtype=int32)

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [6]:
arrayc = np.round((np.random.random((4,6)) * 90),2)
arrayc

array([[ 1.9 , 33.76, 49.71, 89.42, 83.94, 79.19],
       [69.64, 74.07, 35.53, 27.28, 81.88,  3.64],
       [65.69, 23.23, 29.62, 50.73, 51.77, 66.35],
       [72.5 , 89.6 , 29.91, 47.07, 40.71, 52.33]])

In [7]:
arrayc[-1:]

array([[72.5 , 89.6 , 29.91, 47.07, 40.71, 52.33]])

Funciones Aritméticas y Estadísticas:
Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [8]:
arrayd = np.round(np.random.random((2,3,5)), 1)  # Primero se definen en número de matrices, luego filas y al final columnas
arrayd

array([[[0.4, 0.9, 0.4, 0.7, 0.8],
        [0.9, 0.6, 0.5, 0.1, 0.9],
        [0. , 0.3, 0.2, 0.2, 0.6]],

       [[0.9, 0.8, 0.1, 0.3, 1. ],
        [0. , 0.6, 0.9, 1. , 0. ],
        [0.3, 0.2, 0.7, 0.8, 0.9]]])

Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 

In [9]:
arraye = np.empty((2,3,5)) #Devuelve el anterior array, pero está vacío
arraye

array([[[0.4, 0.9, 0.4, 0.7, 0.8],
        [0.9, 0.6, 0.5, 0.1, 0.9],
        [0. , 0.3, 0.2, 0.2, 0.6]],

       [[0.9, 0.8, 0.1, 0.3, 1. ],
        [0. , 0.6, 0.9, 1. , 0. ],
        [0.3, 0.2, 0.7, 0.8, 0.9]]])

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [10]:
media = np.mean(arrayd)
maximo = np.max(arrayd)
minimo = np.min(arrayd)

In [13]:
arraye = np.where(arrayd == maximo, 'D',
          np.where(arrayd == minimo, 'E',
          np.where(arrayd == media, 'A',
          np.where(arrayd > media, 'B','C'))))

arraye

array([[['C', 'B', 'C', 'B', 'B'],
        ['B', 'B', 'C', 'C', 'B'],
        ['E', 'C', 'C', 'C', 'B']],

       [['B', 'B', 'C', 'C', 'D'],
        ['E', 'B', 'B', 'D', 'E'],
        ['C', 'C', 'B', 'B', 'B']]], dtype='<U1')

Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [14]:
array3d = np.random.randint(0, 101, size=(2, 3, 5))
array3d

array([[[ 18,  67,  73,  85,  95],
        [ 66,  97,  61,  98,   4],
        [ 67,  75,  32,  79,  73]],

       [[ 29, 100,  21,  98,  27],
        [ 41,  67,  72,  74,  31],
        [ 68,   1,  98,   5,   4]]], dtype=int32)

In [20]:
flat_array = array3d.flatten()
flat_array[::3] = 0
array4 = flat_array.reshape(2, 3, 5)

array4



array([[[  0,  67,  73,   0,  95],
        [ 66,   0,  61,  98,   0],
        [ 67,  75,   0,  79,  73]],

       [[  0, 100,  21,   0,  27],
        [ 41,   0,  72,  74,   0],
        [ 68,   1,   0,   5,   4]]], dtype=int32)

Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [15]:
array3d_2 = np.random.randint(0, 101, size=(2, 3, 4))
array3d_2

array([[[69, 95,  6, 32],
        [34, 41, 61, 31],
        [ 1, 67, 41,  4]],

       [[64, 76, 95, 28],
        [79, 69,  0, 40],
        [85, 70, 55, 27]]], dtype=int32)

Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [16]:
array3d_3 = np.random.randint(2, 61, size=(3, 4, 5))
array3d_3

array([[[55, 14, 21, 46, 10],
        [ 8, 53, 50,  6, 28],
        [ 2,  5, 19, 54, 59],
        [13, 42, 18, 52, 50]],

       [[29, 35,  3,  9, 53],
        [22, 45, 35, 12, 39],
        [13, 10, 25, 58, 50],
        [18,  4, 45, 42, 35]],

       [[54, 24, 22, 30, 11],
        [57, 36, 60,  8, 10],
        [28, 58, 51, 35, 60],
        [48, 58, 33, 60, 49]]], dtype=int32)

Utiliza el array 3D del ejercicio anterior de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

Utiliza el array 3D del ejercicio anterior 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).